//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mangaya1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class category_manga
    {
        public int id { get; set; }
        public int category_id { get; set; }
        public int manga_id { get; set; }
    
        public virtual category_type category_type { get; set; }
        public virtual manga manga { get; set; }
    }
}
