//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mangaya1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mangayaEntities : DbContext
    {
        public mangayaEntities()
            : base("name=mangayaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<category_manga> category_manga { get; set; }
        public virtual DbSet<category_type> category_type { get; set; }
        public virtual DbSet<chapter> chapters { get; set; }
        public virtual DbSet<chapter_content> chapter_content { get; set; }
        public virtual DbSet<favourit_user> favourit_user { get; set; }
        public virtual DbSet<last_read> last_read { get; set; }
        public virtual DbSet<manga> mangas { get; set; }
        public virtual DbSet<notification> notifications { get; set; }
        public virtual DbSet<report> reports { get; set; }
        public virtual DbSet<salary> salaries { get; set; }
        public virtual DbSet<support> supports { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<translation> translations { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<voicecontent> voicecontents { get; set; }
        public virtual DbSet<voiceoverchapter> voiceoverchapters { get; set; }
    }
}
