//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mangaya1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class salary
    {
        public int id { get; set; }
        public int support_id { get; set; }
        public System.DateTime date { get; set; }
        public float total_profit { get; set; }
    
        public virtual support support { get; set; }
    }
}
