//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mangaya1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class voicecontent
    {
        public int id { get; set; }
        public int chapterid { get; set; }
        public int slide_no { get; set; }
        public string voicelink { get; set; }
    
        public virtual chapter chapter { get; set; }
    }
}
